#!/bin/sh

--skip-action-mailbox
--skip-action-mailer
--skip-action-text
--skip-active-storage
--skip-dev-gems
--skip-jbuilder
--skip-system-test
--skip-test

# Rails 7.2
--skip-rubocop
--skip-ci

--template https://raw.githubusercontent.com/nzwsch/rails-templates/master/template.rb
